#!/usr/bin/env zsh -f
# perform different tasks when network settings are modified
#
# From:	Timothy J. Luoma
# Mail:	luomat at gmail dot com
# Date:	2013-05-16

NAME="$0:t:r"

PPID_NAME=$(ps -cp "$PPID" | fgrep -v 'PID TTY')

case "$PPID_NAME" in
	*launchd*)
						# We don't want to go too fast because when a Mac first wakes up it needs to
						# re-establish its network connection. 15 seconds is plenty of time. You
						# could make it shorter but I would make it at least 5.
					sleep 15

					LOG="$HOME/Desktop/$NAME.log"

					touch "$LOG"

					tell () { echo "$NAME: $@" >> "$LOG" }
					LAUNCHD=yes
	;;

	*)				# These settings are used when the script is not called via `launchd`
					LAUNCHD=no

					tell () { echo "$NAME: $@" }
	;;

esac

	# This will get the current SSID of the Wi-Fi network that you are attached to. IF any.
	#
	# If blank, either the computer is not connected to any Wi-Fi networks, or the AirPort interface is disabled or turned off
	#
SSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk -F': ' '/ SSID/{print $NF}')

	#	We compare the SSID we found against those we have been told about:
case "$SSID" in

	"Home SSID")
						tell "This is your home network"
	exit 0
	;;

	"My Work SSID")
						tell "This is your work network"
	exit 0
	;;

esac

tell "This network is unknown. The SSID is: $SSID."


####|####|####|####|####|####|####|####|####|####|####|####|####|####|####
#
#	TO DISABLE OPENING LOG: Delete this section or put # at the start of each line
#
if [ "$LAUNCHD" = "yes" ]
then
		echo "\n(Note: This file was generated by $0. You can disable this message by opening $0 in a Text Editor and scroll to the bottom to find the 'TO DISABLE OPENING LOG' section.)" >> "$LOG"
		open -t "$LOG"
fi
#
#
#
####|####|####|####|####|####|####|####|####|####|####|####|####|####|####

exit 0
# END OF FILE
